MIN_SCORE = 1
MAX_SCORE = 10
MESSAGE = f'Оценка должна бытьне меньше {MIN_SCORE} и не больше{MAX_SCORE}'
MAX_LENGTH_CAT_AND_GENRE_NAME = 256
MAX_LENGTH_CAT_AND_GENRE_SLUG = 50
MAX_LENGTH_TITLE_NAME = 256
MAX_TO_SHOW = 50
