MIN_SCORE = 1
MAX_SCORE = 10
MESSAGE = f'Оценка должна бытьне меньше {MIN_SCORE} и не больше{MAX_SCORE}'
MAX_LENGTH_CAT_AND_GENRE_NAME = 256
MAX_LENGTH_CAT_AND_GENRE_SLUG = 50
MAX_LENGTH_TITLE_NAME = 256
MAX_TO_SHOW = 50
CATEGORY_CSV = 'category.csv'
GENRE_CSV = 'genre.csv'
USERS_CSV = 'users.csv'
TITLES_CSV = 'titles.csv'
GENRE_TITLE_CSV = 'genre_title.csv'
REVIEW_CSV = 'review.csv'
COMMENTS_CSV = 'comments.csv'
